server:
  port: 80
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: root
        url: jdbc:mysql://localhost:3306/mydatabases?characterEncoding=UTF-8
        username: root
    jackson:
        serialization:
            indent-output: true
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true


    redis:
       database: 0
       host: 192.168.22.45
       port: 8099
       password: xiaoxiaoqaz
       timeout: 0
       pool:
           max-active: 8
           max-wait: -1
           max-idle: 8
           min-idle: 0
    session:
      store-type: none